### ISSUE TITLE
Proposed changes and additions to library before release

### ISSUE THREAD

**Issue by rcfree** [rcfgroup/headfake#10]
Some ideas for additions which I think will be needed before releasing v1.

## Configuration
- Problem with ordering of fields, so it may be good to support a list of fields to simplify this:
e.g.
```yaml
fieldset:
  class: headfake.Fieldset
  - field: main_pat_id:
     class: headfake.field.IdField
     prefix: S
     generator:
      class: headfake.field.IncrementIdGenerator
      length: 7
      min_value: 1000000

    transformers:
      - class: headfake.transformer.UpperCase

  -field: gender:
      class: headfake.field.GenderField
      male_value: "M"
      female_value: "F"
      male_probability: 0.3

```
 
## New fields

- NumberField - including number of DP, min and max and support for distributions
- RepeatJoinField - repeats multiple generations of the field and joins them together
- TextField - random small/large text data (min/max size)
- DateField - random date (min/max, poss support)
- IfElseField/SelectCaseField - see #3 

## Changes to fields
- Deprecate ConstantField - this should be handled through scalar value in YAML
- Add 'internal_field' property allowing intermediate fields to be excluded from output. Could also be done using an 'ExcludeFromOutput' transformer.

## Outputs
- Probably need to streamline this, so FileOutput should become TextFileOutput (with support for field separator)
- Add JsonFileOutput.
