### ISSUE TITLE
Proposal for conditional fields

### ISSUE THREAD

**Issue by rcfree** [rcfgroup/headfake#3]
Seems the best approach to handle this is to create IfElseFields which can be nested. An example of how this could work is given below. A 'title' field is generated based on gender and marital_status:

```yaml
title:
    class: headfake.field.IfElseField
    condition:
        field: gender
        operator: equals
        value: M
    true:
        class: headfake.field.ConstantField
        value: MR
    false:
        class: headfake.field.IfElseField
        condition:
            field: marital_status
            operator: equals
            value: M
        true: MRS
        false: 
            class: OptionValueField
            probabilities:
                MISS: 0.7
                MS: 0.1
                DR: 0.1
                PROF: 0.1
```

This could be very flexible particularly if able to support output through different types of fields depending on the condition.
